leader_key = "f12"

# Applications
b = ["Zen", "browser"]
f = ["Finder", "files"]
t = ["WezTerm", "terminal"]

[a]
label = "[applications]"
a = ["ChatGPT", "ai"]
c = ["Google Chrome", "chrome"]
k = ["KeePassXC", "keepass"]
m = ["Telegram Desktop", "messages"]
n = ["Obsidian", "notes"]
o = ["Microsoft Outlook", "outlook"]
t = ["Microsoft Teams", "ms teams"]
v = ["Visual Studio Code", "vscode"]

# Window management
[w]
label = "[window]"
h = ["function:moveWindowToWestScreen", "west screen"]
l = ["function:moveWindowToEastScreen", "east screen"]
j = ["function:minimizeWindow", "minimize"]
k = ["function:toggleMaximizeWindow", "maximize"]
f = ["function:fullscreenWindow", "fullscreen"]

