return {
--     {
--         "zbirenbaum/copilot.lua",
--         cmd = "Copilot",
--         event = "InsertEnter",
--         config = function()
--             require("copilot").setup({})
--         end,
--     },
--     {
--         "zbirenbaum/copilot-cmp",
--     },
--     {
--         "CopilotC-Nvim/CopilotChat.nvim",
--         dependencies = {
--             { "zbirenbaum/copilot.lua" }, -- or github/copilot.vim
--             { "nvim-lua/plenary.nvim" },  -- for curl, log wrapper
--         },
--         build = "make tiktoken",          -- Only on MacOS or Linux
--         opts = {
--             context = 'buffers',
--         },
--     },
}
